### ISSUE TITLE
Hard lock up while indexing multiple files and cache directory is on ZFS

### ISSUE THREAD

**Issue by ldmosquera** [darrenldl/docfd#10]
`docfd` locks up into 100% CPU usage with all these conditions:
  - only when cache dir is in a ZFS filesystem
  - only when given more than one file argument, or a directory containing more than one file
  - only when indexing previously unseen files (does not happen when reassessing already indexed files, even with cache dir on ZFS)

Is there maybe something unusual you are doing with the filesystem API, which might affect ZFS but not other filesystems, and which interacts with indexing in parallel?

When the lock up happens:
 - it fully pegs all cores
 - does not respond to SIGSTOP or SIGTERM or anything else
 - SIGKILL puts it into an unkillable D state
 - the only recourse is to reboot the machine

In case it helps:

``` bash
$ grep ^PRETTY_NAME /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"

$ uname -a
Linux docfd 6.11.5+bpo-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.11.5-1~bpo12+1 (2024-11-11) x86_64 GNU/Linux

$ zfs --version
zfs-2.2.6-1~bpo12+3
zfs-kmod-2.2.6-1~bpo12+3
```

Reproduction (current dir is on ZFS, `/tmp` is tmpfs):
``` bash
# input is some markdown files
$ find minecraft_changelogs/ -type f -name \*.md -exec du -hc {} +
1K      minecraft_changelogs/32385811139085-Minecraft-Java-Edition-1-21-4-The-Garden-Awakens.html.md
21K     minecraft_changelogs/13987663727757-Minecraft-Java-Edition-1-19-4.html.md
5.0K    minecraft_changelogs/8204540058253-Minecraft-Java-Edition-1-19-2.html.md
21K     minecraft_changelogs/6731464524941-Minecraft-Java-Edition-1-19.html.md
9.0K    minecraft_changelogs/360030771451-Minecraft-Java-Edition-1-14-3.html.md
5.0K    minecraft_changelogs/26295913311885-Minecraft-Java-Edition-1-20-6.html.md
41K     minecraft_changelogs/27547857163917-Minecraft-Java-Edition-1-21-Tricky-Trials.html.md
13K     minecraft_changelogs/360037384972-Minecraft-Java-Edition-Buzzy-Bees.html.md
5.0K    minecraft_changelogs/360028919851-Minecraft-Java-Edition-1-14-2.html.md
33K     minecraft_changelogs/31261174284557-Minecraft-Java-Edition-1-21-2-Bundles-of-Bravery.html.md
21K     minecraft_changelogs/19703470383757-Minecraft-Java-Edition-1-20-2.html.md
9.0K    minecraft_changelogs/4404449719949-Minecraft-Java-Edition-1-17-1.html.md
17K     minecraft_changelogs/4415128577293-Minecraft-Java-Edition-1-18.html.md
5.0K    minecraft_changelogs/360038800232-Minecraft-Java-Edition-1-15-2.html.md
57K     minecraft_changelogs/26136167989005-Minecraft-Java-Edition-1-20-5-Armored-Paws.html.md
5.0K    minecraft_changelogs/4416161161101-Minecraft-Java-Edition-1-18-1.html.md
5.0K    minecraft_changelogs/360038054332-Minecraft-Java-Edition-1-15-1.html.md
17K     minecraft_changelogs/11280166737293-Minecraft-Java-Edition-1-19-3.html.md
9.0K    minecraft_changelogs/360030780172-Minecraft-Java-Edition-1-14-4.html.md
5.0K    minecraft_changelogs/22046600558221-Minecraft-Java-Edition-1-20-4.html.md
5.0K    minecraft_changelogs/29100721259021-Minecraft-Java-Edition-1-21-1.html.md
5.0K    minecraft_changelogs/31289611893645-Minecraft-Java-Edition-1-21-3.html.md
5.0K    minecraft_changelogs/360007323492-Minecraft-Java-Edition-1-13-Update-Aquatic.html.md
25K     minecraft_changelogs/360044911972-Minecraft-Java-Edition-Nether-Release.html.md
25K     minecraft_changelogs/16499677456781-Minecraft-Java-Edition-1-20-Trails-Tales.html.md
5.0K    minecraft_changelogs/360055096392-Minecraft-Java-Edition-1-16-5.html.md
5.0K    minecraft_changelogs/4531177623437-Minecraft-Java-Edition-1-18-2.html.md
399K    total

$ alias docfd_index='docfd --index-only --exts=md'

# cache on tmpfs: OK
$ time docfd_index --cache-dir=/tmp/cache_on_tmpfs minecraft_changelogs/ >/dev/null
real    0m0.952s
user    0m1.619s
sys     0m0.285s

# cache on ext4: OK
$ df --output=fstype cache_on_ext4/
Type
ext4
$ time docfd_index --cache-dir=cache_on_ext4 minecraft_changelogs/ > /dev/null
real    0m0.921s
user    0m1.781s
sys     0m0.219s

# cache on ZFS but no unseen files (so no new indexing): OK
$ rsync -a /tmp/cache_on_tmpfs/ cache_on_zfs
$ time docfd_index --cache-dir=cache_on_zfs minecraft_changelogs/ >/dev/null
real    0m0.285s
user    0m0.953s
sys     0m0.124s

# cache on ZFS but one file at a time: OK
$ rm -rf cache_on_zfs
$ time for i in minecraft_changelogs/*.md; do docfd_index --cache-dir=cache_on_zfs "$i"; done >/dev/null
real    0m1.873s
user    0m3.378s
sys     0m0.492s

# cache on ZFS with more than one file to index: game over
$ rm -rf cache_on_zfs
$ docfd_index --cache-dir=cache_on_zfs minecraft_changelogs/

Scanning ✔️
Collecting file stats
[00:00] [##################] 100% ETA: 30744
- File count:     27
- MiB:             0.6
Hashing
[00:00] [##################] 100%  242.1 MiB/s ETA: 30744
Finding and loading indices
- File count:      0
- MiB:             0.0
[00:00] [------------------]   0%    0.0 B  /s ETA: 30744
Processing files with index
Indexing remaining files
- File count:     27
- MiB:             0.6
[00:00] [------------------]   0%    0.0 B  /s ETA: 30744
```

**Comment by ldmosquera** [comment]
You can probably disregard+close; it seems very similar to this:

https://github.com/openzfs/zfs/issues/16133

also affecting an OCaml program. It appears to be a kernel bug (either in ZFS or in a syscall used by OCaml) and not a `docfd` bug in particular.

I hope this at least demystifies it for the next person stumped by this. `docfd` is very interesting!

**Comment by darrenldl** [comment]
Thanks very much for the detailed reporting and also finding the related issue! Yeah one of the libraries uses io_uring as a backend I think, and that hits exactly the issue you linked I suspect.

I will keep tabs on the issue and see if there will be any update I need to do on my end. Alternatively I may just introduce another build pipeline to use a different backend for zfs systems when I get to it.

But right now the focus (when I have time to work on docfd) is to redesign the index code to support many GBs of documents by using an on-disk SQLite db as index. Currently it blows up the memory when you have many documents.

> docfd is very interesting!

Thank you for your interest! Searching through changelog alike was one of the core considerations during its design, so you picked the right tool dare I say.

**Comment by darrenldl** [comment]
@ldmosquera Could you try this build https://github.com/darrenldl/docfd/actions/runs/12514610306/artifacts/2365479825 ? (Same GitHub CI workflow, but on `ci-test` branch instead of on tag, so the URL looks different.)

I simply swapped to no longer using the io_uring backend. Hopefully this alleviates the issue.

This build also uses the new code for sqlite index - I would be interested in knowing if it runs smoothly for you with this major update.

**Comment by ldmosquera** [comment]
No more spinlock when caching ZFS! Great success.

Thanks a lot :)
