### ISSUE TITLE
FYI: Now available from ArchLinux User Repository (AUR)

### ISSUE THREAD

**Issue by kseistrup** [darrenldl/docfd#4]
This issue is informative only, and you may close it at your discretion. No action is needed on your part unless you wish to include the information in the README.

The pre-compiled release binary of `docfd` is now available from AUR:

* https://aur.archlinux.org/packages/docfd-bin

It can be installed using an AUR helper:

* https://wiki.archlinux.org/title/AUR_helpers

E.g., `yay`:

```sh
yay -S docfd-bin
```

:pray:

**Comment by darrenldl** [comment]
Thanks! I've updated the README accordingly.

Also re attribution: what is your preferred way of linking/attribution? To your codeberg account or Microsoft github account? (Or another method)

**Comment by darrenldl** [comment]
Understood. I'll leave it at gh then if you have no preference. Thanks again!

**Comment by darrenldl** [comment]
Hey @kseistrup

Just FYI, 2.2.0 is out. It has some fixes, improvements, and the search expression feature is properly documented now.

**Comment by kseistrup** [comment]
@darrenldl 

Thanks for reaching out, I just updated the AUR package a few minutes ago:

* https://aur.archlinux.org/packages/docfd-bin

Microsoft GitHub automatically sends me a notification whenever you release a new version (or announce a security issue), so it's okay for you to be forgetful about AUR. And it's also okay to say hello, of course, so thanks for the notification. :pray:
