### ISSUE TITLE
FYI: Now available in Nixpkgs

### ISSUE THREAD

**Issue by chewblacka** [darrenldl/docfd#5]
Just an FYI. I've pacakged [docfd for Nix](https://search.nixos.org/packages?channel=unstable&show=docfd&from=0&size=50&sort=relevance&type=packages&query=docfd). Currently available on nixpkgs unstable, and NixOS unstable. Will be added to the next stable release of NixOS, 24.05 in May.  It is reproducibly built from source and can be installed on any linux / mac environment which has nix installed. Nix can be installed with e.g. the [Determinate Systems Nix installer](https://github.com/DeterminateSystems/nix-installer). 

If using the above nix installer, docfd can be installed with the command: `nix profile install nixpkgs#docfd`

Hope that info is useful. Many thanks.

**Comment by darrenldl** [comment]
Oh nice! Thanks! I've updated README to reflect this.

Glad you like docfd, hope you'll find 2.2.0 even better.

Does github automatically notify you w.r.t. releases as well?

**Comment by chewblacka** [comment]
> Does github automatically notify you w.r.t. releases as well?

Yes I'm signed up to receive notifications of new releases. Glad to see development is proceeding apace & looking forward to trying the new version! Many thanks.

**Comment by darrenldl** [comment]
Gotcha, thanks!
