### ISSUE TITLE
generic linux version

### ISSUE THREAD

**Issue by pcause** [darrenldl/docfd#9]
Can you provide an appimage version.   thanks

**Comment by darrenldl** [comment]
How does it compare to a statically linked binary? I'm not familiar with appimage at all

**Comment by pcause** [comment]
same.

**Comment by darrenldl** [comment]
Does the [static build](https://github.com/darrenldl/docfd/releases/download/7.0.0/docfd-7.0.0-ubuntu-latest.tar.gz) not work? (The ubuntu just means it's built on ubuntu, but should work on any distro.)

**Comment by pcause** [comment]
sorry, when I see ubuntu in the name I assume it is ubuntu specific.  will try and you might want to change the name if it is static.  others just use "linux" in the name and not a specific distro.

**Comment by pcause** [comment]
seemed to work.  thanks.

**Comment by darrenldl** [comment]
> sorry, when I see ubuntu in the name I assume it is ubuntu specific. will try and you might want to change the name if it is static. others just use "linux" in the name and not a specific distro.

That is a good point. The default github workflow just adds the OS name so I didn't give any further thought. Thanks for the suggestion!

**Comment by darrenldl** [comment]
I've amended it so future releases will read `docfd-VER-linux.tar.gz` instead.
